package com.aston728.engine.core.internals.devices

import org.lwjgl.glfw.GLFW.*

public enum class Cursor(private val cursor: Int) {
    ARROW(GLFW_ARROW_CURSOR),
    HAND(GLFW_HAND_CURSOR),
    POINTING_HAND(GLFW_POINTING_HAND_CURSOR),
    CROSSHAIR(GLFW_CROSSHAIR_CURSOR),
    IBEAM(GLFW_IBEAM_CURSOR),
    HORIZONTAL_RESIZE(GLFW_RESIZE_EW_CURSOR),
    VERTICAL_RESIZE(GLFW_RESIZE_NS_CURSOR),
    LTR_DIAGONAL_RESIZE(GLFW_RESIZE_NWSE_CURSOR),
    RTL_DIAGONAL_RESIZE(GLFW_RESIZE_NESW_CURSOR),
    OMNI_DIRECTIONAL_RESIZE(GLFW_RESIZE_ALL_CURSOR),
    NOT_ALLOWED(GLFW_NOT_ALLOWED_CURSOR);

    internal fun toGLFWCursor(): Int = this.cursor
}
